UPEI-Android/virtual-wellness-project

composer.lock, database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2022_01_31_015950_create_treat_group_table.php, package-lock.json
#33  Adding orm for users and the initial table for treatment groups to the migrations. I am sure that more will be added to both as we continue development.
=> Jared orm for users

resources/css/app.css, resources/js/ReactRenderer.js, resources/js/app.js, resources/js/components/Header.js, resources/views/layouts/app.blade.php, webpack.mix.js
There is now a navBar component called "Header" that can be included in any other component. Styling will be changed once css is ironed out
=> Jared top nav bar

app/Http/Controllers/TreatmentController.php, app/Http/Kernel.php, app/Http/Middleware/MustBeAdministrator.php, app/Models/Treatment.php, database/factories/TreatmentFactory.php, database/migrations/2022_02_28_015325_create_treatments_table.php, phpunit.xml, resources/views/treatments/index.blade.php, resources/views/treatments/show.blade.php, routes/web.php, tests/Feature/TreatmentTest.php, tests/Unit/TreatmentTest.php, tests/Unit/UserTest.php
#57 working on it and explained the changes in meetings 
Feature tests created for treatments 
3 routes created through Treatment Controller 
HTML views available for the routes 
Middleware admin created to define user type so user table updated 
UserTest created for admin and patients 
Pass patient id eloquent relationship feature test too
=> Shi tests treatment

app/Http/Controllers/TreatmentController.php, app/Http/Resources/TreatmentResource.php, app/Models/Treatment.php, database/factories/UserFactory.php, database/migrations/2014_10_12_000000_create_users_table.php, database/migrations/2022_01_31_015950_create_treatment_group_table.php, database/seeders/DatabaseSeeder.php, routes/api.php, routes/web.php, tests/Feature/ManagingTreatmentTest.php, tests/Feature/TreatmentTest.php
Old tests are now called ManagingTreatmentTest, they were for web routes, don't run as auth is not setup, api works without auth layer, preliminary test for index API is done
=> API works for Treatments

package.json, resources/js/components/pages/Users/UserProfileContainer.js
Everything is hard coded except name, email, and ID
(added a comma to package.json which was missing)
=> Just prettying up the fields in user profile

app/Http/Controllers/RulesController.php, app/Http/Controllers/UserController.php, app/Http/Requests/TreatmentRequest.php, app/Models/Rule.php, app/Models/Treatment.php, app/Models/User.php, database/migrations/2022_02_28_015325_create_treatments_table.php, database/migrations/2022_03_16_084941_create_rules_table.php, database/seeders/DatabaseSeeder.php, tests/Feature/TreatmentTest.php, tests/Unit/RulesTest.php, tests/Unit/TreatmentTest.php, tests/Unit/UserTest.php
fixes #95 
All controllers adjusted to manual querying to relationships. Unit tests passed. Could not add a feature test with users not exists error so removed it
=> Relationships for route binding

app/Http/Controllers/TreatmentController.php, public/js/app.js, resources/js/app.jsx, resources/js/components/SideBar/NavItem.jsx, resources/js/components/SideBar/SideBarNav.jsx, resources/js/components/Treatment/TreatmentFilters.jsx, resources/js/components/Treatment/TreatmentForm.jsx, resources/js/components/Treatment/TreatmentList.jsx, resources/js/components/Treatment/TreatmentListCopy.jsx, resources/js/components/Treatment/TreatmentOverview.jsx, resources/js/components/Treatment/TreatmentOverviewContainer.jsx, resources/js/components/Treatment/noTreatments.jsx, resources/js/components/store/actions/TreatmentActions.js, resources/js/components/store/reducers/TreatmentReducer.js, resources/js/hooks/useFetch.js, resources/views/treatmentViews/indexOfTreatments.blade.php, routes/api.php, routes/web.php
connected treatment to backend to pull treatments with redux
issue #94
=> Liz connecting

app/Http/Controllers/UserController.php, resources/js/app.jsx, resources/js/components/SideBar/NavItem.jsx, resources/js/components/SideBar/SideBarNav.jsx, resources/js/components/pages/Users/EditUserProfile.js, resources/js/components/pages/Users/UserProfile.js, resources/js/components/pages/Users/UserProfileContainer.js, resources/js/components/store/actions/UserActions.js, resources/views/users/userprofile.blade.php, routes/web.php
Changed user profile route so it now works in the sidebar and the api call is now dynamic to bring up whatever user is logged in. Now that the auth is added the api call gets rejected though
=> Jared userprofiledynamic

app/Http/Controllers/UserController.php, database/migrations/2014_10_12_000000_create_users_table.php, resources/js/app.jsx, resources/js/components/pages/Users/EditProfile.js, resources/js/components/pages/Users/EditUserProfile.js, resources/js/components/pages/Users/UserProfile.js, resources/views/users/editprofile.blade.php, routes/web.php
Initial user works for updating the user table in the database. no validation yet but will be added in next iteration.
=> Jared initialedituser

resources/js/components/pages/Users/EditProfile.jsx, resources/js/components/pages/Users/EditProfileContainer.jsx, resources/js/components/pages/Users/EditUserProfile.jsx, resources/js/components/pages/Users/UserProfile.jsx, resources/views/users/editprofile.blade.php, routes/web.php
That 429 error from the meeting today... caused by me missing two dang brackets
Also fixed an issue with the current userid being passed to the editprofile page
=> fixed a couple errora

public/js/app.js, resources/js/components/Treatment/CreateTreatment.jsx, resources/js/components/Treatment/CreateTreatmentContainer.jsx
passed patient id from user instead of hardcoded
issue #123
=> pass user id to create treatment form

app/Http/Controllers/WelcomeController.php, public/js/app.js, resources/js/components/Treatment/CreateTreatment.jsx, resources/js/components/Treatment/CreateTreatmentContainer.jsx, resources/js/components/Treatment/TreatmentContainer.jsx, resources/js/components/Treatment/TreatmentList.jsx, resources/js/components/store/reducers/TreatmentReducer.js, resources/views/treatmentViews/createTreatment.blade.php, routes/web.php
=> A Few Fixes by Liz

resources/css/app.css, resources/js/components/pages/Users/EditProfile.jsx, resources/js/components/pages/Users/UserProfile.jsx
Just some style fixes for the profile. Button looks like other buttons and kept the component from covering sidebar
=> Fixing bugs and Styling issues with user profile

app/Http/Requests/TreatmentRequest.php, resources/js/components/Treatment/TreatmentList.jsx, resources/js/components/pages/Users/EditProfile.jsx
added notes to treatment request, just a temporary fix 
properly finding treatment for saving the treatments
=> Fixes for createTreatment and saveTreatment 

public/js/app.js
=> app js troubleshooting

public/js/app.js
=> Liz-app-js-fix

app/Http/Controllers/TreatmentController.php
=> store function revert

app/Http/Controllers/TreatmentController.php, public/js/app.js, resources/js/components/Treatment/CreateTreatment.jsx, resources/js/components/pages/Users/EditProfile.jsx, resources/js/components/store/actions/UserActions.js
added treatment buildout of front end
=> readded treatment rules to create treatment page

app/Http/Requests/TreatmentRequest.php, app/Models/Treatment.php, tests/Feature/TreatmentTest.php
The recommendation is to switch to API resources for correct formatting of relationships, specifically, the treatments which has relationship with users and rules, so was hard to debug, and validation turned out to be  blocking the store, which is also implemented
=> Store fixed

public/.htaccess
=> Fixing Post Request 301 issue on Create Treatment

public/js/app.js, resources/js/components/Treatment/TreatmentList.jsx
possible bandaid fix for reloading components on changes by trackin all local states
=> delete and is_completed reload fix

app/Http/Controllers/TreatmentController.php, resources/js/components/pages/Users/EditProfile.jsx, resources/js/components/store/actions/TreatmentActions.js
changed the data being passed to a raw json file rather than the unintended json wrapped in a object called 'state'
=> Fixed the issue passing treatments to update

app/Http/Controllers/UserController.php, database/migrations/2014_10_12_000000_create_users_table.php, resources/js/components/pages/Users/EditProfile.jsx, resources/js/components/pages/Users/UserProfile.jsx
Adding gender and age as parts of the db
=> Adding gender and age to user db and other user pages

app/Http/Controllers/RulesController.php, app/Services/RulesService.php, tests/Feature/RulesTest.php
fixes #140 
Rules Controller now assign an integer to just make sure it is not an infinite occurrence of dates and the controller and its tests were adjusted and they all pass
=> Rules Enhanced
